### PR TITLE
DSS-1967-Mock-BQ-and-Transfer

### PR DESCRIPTION
**Pull request by ghasani**
Adding mocking to unit tests and slight refactor to methods.

### CODE REVIEW

**Review by Munir93 — APPROVED** [review]
LGTM!

**Comment by kthhrv** [comment]
@ghasani you'll want me to force merge this? as the tests haven't yet all be changed to mock

**Comment by ghasani** [comment]
> @ghasani you'll want me to force merge this? as the tests haven't yet all be changed to mock

No thanks, working on mocking the others too so the build will pass and we can merge then

**Review by kthhrv — APPROVED** [review]
LGTM

**Pull request merged**
