### PR TITLE
DSS 1901 - GCS Unit Tests

### PR DESCRIPTION
**Pull request by ghasani**
Writing unit tests for new functionality we have in GCS client that wraps around client methods.

### CODE REVIEW

**Comment by kthhrv** [comment]
pr tests are failing with liniting, do you have `pre-commit` installed in your repo clone?

`$ pre-commit install`

you can run `$ pre-commit run --all-files` to get the required changes made in your clone

**Review by kthhrv — CHANGES_REQUESTED** [review]
fix linitng

**Comment by ghasani** [comment]
> fix linitng
done thanks

**Review by kthhrv — APPROVED** [review]
LGTM I'll force merge as there are still tests that require changing to use mock blocking th merge

**Pull request merged**
